i3config syntax with better keyword/type distinction
vim/vim pull request #10600
Opened 2022-06-20 18:30 UTC by JosefLitos

This syntax uses a couple more colour highlights to match the actual function of used keywords in the config file. This way it is easier to figure out what does what.
- distinctly highlights key combos to clearly differentiate it from the rest of the command
- all keywords that can be used as command line commands are highlighted as Functions
- conditions are now properly highlighted with all operators clearly visible
+ some bug fixed

2022-06-20 19:32 UTC, hiqua commented
Thanks! Will review.

2022-07-06 18:16 UTC, hiqua requested changes
I know it's a long shot, but, before I deep-dive into the code to review it, any chance you could try to reduce the diff? That would make my life way easier.

Otherwise I'll make do with this, but it might take me more time.

2022-07-06 18:16 UTC, hiqua commented on runtime/syntax/i3config.vim
> +" Maintainer: Josef Litoš (github JosefLitos)
Sure about that? :smile:

2022-07-06 18:16 UTC, hiqua commented on runtime/syntax/i3config.vim
> +" Version: 4.20
I guess we can remove the version line altogether, it makes little sense IMHO.

2022-07-06 18:16 UTC, hiqua commented on runtime/syntax/i3config.vim
> +syn match i3ConfigError /.*/
I've removed that already in a separate commit, can you remove it as well? It poses problem whenever a new keyword is introduced e.g. in sway, and we're not fully up to date, which is bound to happen regularly.

2022-07-08 08:14 UTC, JosefLitos commented
I will get to it as soon as I can (in August).

2022-07-24 10:40 UTC, JosefLitos commented
I reorganized it a little. But the color binds I left untouched as I find it a little clearer this way.

2022-07-25 20:27 UTC, hiqua commented
Thanks! I'll have a look.

2022-10-30 08:43 UTC, hiqua commented
Hi @JosefLitos, sorry I took some time, and now your PR seems to have conflicts and failing the CI, can you rebase it before I delve into it? I promise I won't be that long after that.

2022-10-31 07:20 UTC, JosefLitos commented
@hiqua I am a little afraid I did the rebase procedure incorrectly as all the new commits have been made. But it shouldn't interfere with master anymore.

2023-06-26 06:32 UTC, closed without merging