feat: solidity.vim of syntax
vim/vim pull request #11240
Opened 2022-09-27 07:31 UTC by cothi

hi, I looked it up and found that the syntax solidity file was missing. How about supporting solidity syntax?

2022-09-27 11:56 UTC, brammool commented
Is this one better than the previous PR?

2022-09-27 11:57 UTC, brammool commented
The file does not set b:current_syntax

2022-09-27 13:17 UTC, cothi commented
There was a bit of confusion about licensing. So I made a mistake, then I PR it again.
 I corrected `the source code typo`, and  I added a modified source code
, so please check it out

thank you

2022-09-27 13:26 UTC, k-takata commented
The original repository (https://github.com/tomlion/vim-solidity) has not only the syntax file but also the indent file and the ftplugin file.
Are you going to take over the maintenance of the syntax file only?

2022-09-27 14:01 UTC, cothi commented
I added the necessary file for solidity (`indent`, `ftplugin`)

2023-08-17 14:11 UTC, dkearns requested changes
The indent plugin needs to have `b:undo_indent` set as well to undo the setting of `'smartindent'`, `'indentexpr'` and `'indentkeys'`.  See `:help undo_indent` for details.

2023-08-17 14:11 UTC, dkearns commented on runtime/ftplugin/solidity.vim
> +setlocal commentstring=//\ %s
`b:undo_ftplugin` needs to be set. See `:help undo_ftplugin`

Setting `'comments'` as well while you're here would be a good idea.

2023-08-17 14:11 UTC, dkearns commented on runtime/ftplugin/solidity.vim
> +" Original author: tomlion (https://github.com/tomlion/vim-solidity)
Simply using `Author:` here is more 'standard' and is recognised by the syntax highlighters.

2023-08-17 14:11 UTC, dkearns commented on runtime/indent/solidity.vim
> +" Original author: tomlion (https://github.com/tomlion/vim-solidity)
Simply using Author: here is more 'standard' and is recognised by the syntax highlighters.

2023-08-20 19:26 UTC, chrisbra commented
@cothi any updates please?

2023-08-22 18:28 UTC, closed without merging