feat(heex): borrow matchit support from html
vim/vim pull request #12717
Opened 2023-07-30 16:17 UTC by cvincent

Makes `%` behave the same in heex as in html. For example, quickly moving the cursor between opening and closing tags.

2023-08-06 17:57 UTC, dkearns commented
Have you contacted the maintainer listed in the header?

2023-08-06 17:59 UTC, dkearns requested changes

2023-08-06 17:59 UTC, dkearns commented on runtime/ftplugin/heex.vim
> +  let b:html_set_match_words = 1
This line can be removed.  It only serves a purpose for files sourcing the HTML ftplugin.

2023-08-06 17:59 UTC, dkearns commented on runtime/ftplugin/heex.vim
>  let b:undo_ftplugin = 'set sw< sts< et< com< cms<'
This line needs to be moved to above the conditional Matchit settings - line 25 is appending to an undefined variable.

2023-08-07 13:12 UTC, dkearns requested changes
Thanks for the PR. This might take a week or so to be merged as the interim development model is still to be worked out.

2023-08-07 13:12 UTC, dkearns commented on runtime/ftplugin/heex.vim
> +  let b:undo_ftplugin ..= " | unlet! b:match_ignorecase b:match_words b:html_set_match_words"
` b:html_set_match_words` should be removed from `b:undo_ftplugin` value as well.

2023-08-09 10:31 UTC, dkearns commented
LGTM, thanks @cvincent.

2023-08-09 14:49 UTC, chrisbra commented
Thanks, I'll include it.

2023-08-09 14:49 UTC, merged