Implement member type check in interfaces
vim/vim pull request #12844
Opened 2023-08-18 16:14 UTC by LemonBoy

Most of the code is a small refactoring to allow the use of a where_T for signaling the type mismatch, the type checking itself is pretty simple.

2023-08-18 16:53 UTC, yegappan requested changes

2023-08-18 16:53 UTC, yegappan commented on src/vim9type.c
> +	    semsg(_(where.wt_kind
Is it better to use `where.wt_kind != WT_ARGUMENT` here?
or change the check to `where.wt_kind == WT_ARGUMENT` and reverse the values?

2023-08-18 16:53 UTC, yegappan commented on src/vim9type.c
> +	    semsg(_(where.wt_kind
Is it better to use `where.wt_kind != WT_ARGUMENT` here?
or change the check to `where.wt_kind == WT_ARGUMENT` and reverse the values?

2023-08-19 11:06 UTC, closed without merging

2023-08-19 11:07 UTC, chrisbra commented
Thanks. There were some conflicts from #12848 in test_vim9_class.vim  hopefully I resolved them correctly

2023-08-19 12:39 UTC, LemonBoy commented
Ah, that was (too) fast! The CI did not kick in for some reason and now master's broken.
This patch should fix the remaining errors, sorry for the noise.

```patch
diff --git a/src/vim9execute.c b/src/vim9execute.c
index 6c208786a..2eb6ba4ca 100644
--- a/src/vim9execute.c
+++ b/src/vim9execute.c
@@ -5451,8 +5451,8 @@ exec_instructions(ectx_T *ectx)
                    {
                        where.wt_index = ct->ct_arg_idx;
                        where.wt_kind = ct->ct_is_var ? WT_VARIABLE : WT_ARGUMENT;
-                       where.wt_func_name = ectx->ec_where.wt_func_name;
                    }
+                   where.wt_func_name = ectx->ec_where.wt_func_name;
                    r = check_typval_type(ct->ct_type, tv, where);
                    if (r == FAIL)
                        goto on_error;
diff --git a/src/vim9type.c b/src/vim9type.c
index 1363a1c3e..4c1693668 100644
--- a/src/vim9type.c
+++ b/src/vim9type.c
@@ -682,8 +682,8 @@ check_typval_arg_type(
     {
        where.wt_index = arg_idx;
        where.wt_kind = WT_ARGUMENT;
-       where.wt_func_name = func_name;
     }
+    where.wt_func_name = func_name;
     return check_typval_type(expected, actual_tv, where);
 }
```

2023-08-19 14:04 UTC, chrisbra commented
thanks, applied