runtime(cmake): sync runtime files with upstream
vim/vim pull request #13597
Opened 2023-11-29 17:20 UTC by e-kwsm

2023-11-30 10:21 UTC, dkearns requested changes
Thanks for the update.

It looks like this is maintained and distributed as part of the CMake project.  If you're managing updates to the Vim distribution, rather than Dimitri, it might be a good idea to also list yourself as a maintainer in the header and add yourself to https://github.com/vim/vim/blob/master/.github/CODEOWNERS

@chrisbra might have some thoughts on how to manage this scenario.

2023-11-30 10:21 UTC, dkearns commented on runtime/indent/cmake.vim
> -
This should not be removed.

2023-11-30 16:47 UTC, chrisbra commented
Thanks, I don't have anything more to add, you covered it all :)

2023-12-04 20:15 UTC, e-kwsm commented
They were
* https://gitlab.kitware.com/cmake/cmake/-/blob/44a2f3f3324a608062eb7b88072c7640f80f4a5c/Auxiliary/vim/indent/cmake.vim
* https://gitlab.kitware.com/cmake/cmake/-/blob/c1d787e4734ca107e8ae084b3832e441651a6266/Auxiliary/vim/syntax/cmake.vim

MR [cmake!9034](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/9034).

2023-12-04 20:26 UTC, e-kwsm commented
The upstream is https://github.com/pboettch/vim-cmake-syntax.
Consequently this goes to pboettch/vim-cmake-syntax#33.

2023-12-05 15:10 UTC, chrisbra commented
so is this ready? Or is there anything missing?

2023-12-06 15:33 UTC, e-kwsm commented on runtime/indent/cmake.vim
> -
Thank you for your review.

2023-12-06 15:34 UTC, e-kwsm commented
Ready but pboettch/vim-cmake-syntax#33 is not merged.

2023-12-08 20:53 UTC, chrisbra commented on runtime/indent/cmake.vim
> +" Last Change:  2022 Mar 22
Why is the Last Change header now before the old Last Change Header?

2023-12-12 22:07 UTC, e-kwsm commented on runtime/indent/cmake.vim
> +" Last Change:  2022 Mar 22
This was a conflict with this and CMake repositories.

2023-12-14 19:38 UTC, merged