Termdebug: add Tbreak command
vim/vim pull request #13656
Opened 2023-12-10 21:28 UTC by iam28th

Add `:Tbreak` command to insert a temporary breakpoint at the cursor location. 

Currently it can be achieved by using `tbreak` in the gdb-window, but typing the address in there looks much less convenient compared to vim navigation.

2023-12-10 21:31 UTC, chrisbra commented
Thanks. Can you please add a test for this?

2023-12-10 23:17 UTC, iam28th commented
Add test for `Tbreak` functionality. It checks signs in the buffer, similar to what the first part of [Test_termdebug_basic()](https://github.com/vim/vim/blob/master/src/testdir/test_termdebug.vim#L23) does.

2023-12-11 14:41 UTC, iam28th commented
Is there anything else I should do? 
The failed test seems to be about autogenerated index files, so maybe failing this test is not a big deal...

2023-12-11 14:46 UTC, Shane-XB-Qian commented
bram said he donot want to make too many gdb cmd to be termdebug cmd,
so i am thinking if it was really want to add this cmd, how about to be a sub cmd of Break?
// which default is 'Break' which no args, vs if 'Break t[mp]' then same like 'Tbreak' cmd or 'tbreak' gdb cmd?

2023-12-11 14:56 UTC, iam28th commented
I would argue against this, because currently most Termdebug commands that are wrappers around corresponding `gdb` commands use the particular naming scheme (run -> Run, continue -> Continue, etc, the only exception is where this naming clashes with the `:Next` vim command). 
Implementing `tbreak` as `:Break t[mp]` would unexpectedly break this pattern.

I agree that not all `gdb` commands need to have corresponding command in Termdebug, but from my user experience - `tbreak` certainly needs one.

2023-12-11 15:04 UTC, Shane-XB-Qian commented
> I would argue against this, because currently most Termdebug commands that are wrappers around corresponding `gdb` commands use the particular naming scheme (run -> Run, continue -> Continue, etc, the only exception is where this naming clashes with the `:Next` vim command). 
> Implementing `tbreak` as `:Break t[mp]` would unexpectedly break this pattern.

the different is '-break-insert' and '-break-insert -t', so i think it was a special case of 'break'

-- 
shane.xb.qian

2023-12-11 15:10 UTC, iam28th commented
> the different is '-break-insert' and '-break-insert -t', so i think it was a special case of 'break'
> […](#)
> -- shane.xb.qian

From the internal perspective - yes, but not when using `gdb` from the terminal. Here you have separate `break` and `tbreak` commands.

2023-12-11 15:38 UTC, yegappan commented on src/testdir/test_termdebug.vim
> +  " was hit once
Instead of cloning the code from Test_termdebug_basic(), can you try to reuse that?  You can either move the new test to the Test_termdebug_basic() function or move the code for generating a test executable to a common function.

2023-12-11 15:38 UTC, yegappan commented on src/testdir/test_termdebug.vim
> +  edit XTD_basic.c
A different file name should be used.  The "XTD_basic.c" is used in Test_termdebug_basic().

2023-12-11 15:46 UTC, yegappan commented on src/testdir/test_termdebug.vim
> +  Continue
This test doesn't check that the temporary breakpoint is hit only once.  Can you set a temporary breakpoint inside the for loop and a breakpoint in the main function after the call to printf(), then run "Continue" after the first break point is hit to make sure that the breakpoint is not hit again?

2023-12-12 14:41 UTC, iam28th commented on src/testdir/test_termdebug.vim
> +  " was hit once
Moved the code to generate and cleanup test files to functions.

2023-12-12 14:54 UTC, yegappan requested changes
Thanks for making the changes to the test.

2023-12-12 14:54 UTC, yegappan commented on runtime/pack/dist/opt/termdebug/plugin/termdebug.vim
> +  command -nargs=? Tbreak call s:SetBreakpoint(<q-args>, 1)
Can you use "v:true" instead of 1 here?

2023-12-12 14:54 UTC, yegappan commented on runtime/pack/dist/opt/termdebug/plugin/termdebug.vim
> +func s:SetBreakpoint(at, t=0)
Can you use "tbreak = v:false" instead of "t=0"?

2023-12-12 14:54 UTC, yegappan commented on src/testdir/test_termdebug.vim
>    let lines =<< trim END
The single dot for string concatenation is deprecated now.  Can you use ".." here?

2023-12-12 14:54 UTC, yegappan commented on src/testdir/test_termdebug.vim
> +  call delete(a:bin_name . '.c')
Use double dots here.

2023-12-12 14:54 UTC, yegappan commented on src/testdir/test_termdebug.vim
> +  let src_name = bin_name . '.c'
Use double dots here.

2023-12-12 14:54 UTC, yegappan commented on src/testdir/test_termdebug.vim
> +  execute 'Termdebug ./' . bin_name
Use double dots here.

2023-12-12 14:54 UTC, yegappan commented on src/testdir/test_termdebug.vim
> +  let src_name = bin_name . '.c'
Use double dots here.

2023-12-12 14:54 UTC, yegappan commented on src/testdir/test_termdebug.vim
> +  execute "Break " . bp_line
Use double dots here.

2023-12-12 15:07 UTC, yegappan approved these changes

2023-12-12 15:20 UTC, iam28th commented
> The help tags check CI test is failing (https://github.com/vim/vim/actions/runs/7183328851/job/19562047377). You need to run the "make tags" command in the runtime/doc directory and commit the updated tags file.

Out of curiosity - what is the reasoning behind here? This file can always be auto-generated from source during build, so why is there a need to manually update it?

2023-12-12 15:53 UTC, chrisbra commented
Is the test flaky? 
```
command line..script /home/runner/work/vim/vim/src/testdir/runtest.vim[607]..function RunTheTest[57]..Test_termdebug_tbreak line 21: Expected [{'lnum': 10, 'id': 1014, 'name': 'debugBreakpoint1.0', 'priority': 110, 'group': 'TermDebug'}, {'lnum': 22, 'id': 2014, 'name': 'debugBreakpoint2.0', 'priority': 110, 'group': 'TermDebug'}] but got [{'lnum': 22, 'id': 2014, 'name': 'debugBreakpoint2.0', 'priority': 110, 'group': 'TermDebug'}]
```

2023-12-12 15:54 UTC, chrisbra commented
> Out of curiosity - what is the reasoning here? This file can always be auto-generated from source during build, so why is there a need to manually update it?

Basically if people are downloading the runtime files manually, they don't have to generate the help tags file to make use of it with Vim.

2023-12-12 16:21 UTC, iam28th commented
> Is the test flaky?
> 
> ```
> command line..script /home/runner/work/vim/vim/src/testdir/runtest.vim[607]..function RunTheTest[57]..Test_termdebug_tbreak line 21: Expected [{'lnum': 10, 'id': 1014, 'name': 'debugBreakpoint1.0', 'priority': 110, 'group': 'TermDebug'}, {'lnum': 22, 'id': 2014, 'name': 'debugBreakpoint2.0', 'priority': 110, 'group': 'TermDebug'}] but got [{'lnum': 22, 'id': 2014, 'name': 'debugBreakpoint2.0', 'priority': 110, 'group': 'TermDebug'}]
> ```

[This is the line](https://github.com/iam28th/vim/blob/98436b3d5cec338c7926efc2cb7f7eb2a7a5bfab/src/testdir/test_termdebug.vim#L188) where the check fails.

Could be the wait is too short? `call term_wait(gdb_buf)` defaults to 10 ms.
In the master branch, `call term_wait(gdb_buf, 400)` is [used once](https://github.com/vim/vim/blob/2025af165ec68d831f0f0f668a3ceac3f39142ef/src/testdir/test_termdebug.vim#L65) (only after `Run`, though).

Though the result is odd: the second breakpoint has a sign, and the first does not.

<details>
  <summary>Locally I can run this test 100 times without failures:</summary>
  
![image](https://github.com/vim/vim/assets/65417931/a0f16ad2-e6f5-4f91-a47d-00d186cece10)
  
</details>

2023-12-14 19:32 UTC, chrisbra commented
okay thanks. Let me mark it as flaky for now.

2023-12-14 19:34 UTC, closed without merging