runtime(erlang): Add support for matchit plugin
vim/vim pull request #13713
Opened 2023-12-17 20:45 UTC by hcs42

This commit updates the Erlang runtime files to be in sync with the `vim-erlang-runtime` repository. In particular, it adds the following commit: https://github.com/vim-erlang/vim-erlang-runtime/commit/6ea8b85bc9c93b94c68ec53489a74f5687d898b0 (a contribution from @subc2)

2023-12-18 03:31 UTC, dkearns requested changes
Thanks for the PR.

2023-12-18 03:31 UTC, dkearns commented on runtime/ftplugin/erlang.vim
> +  let b:match_skip = 's:comment\|string\|erlangmodifier\|erlangquotedatom'
You should set `b:match_ignorecase` rather than rely on the `'ignorecase'` option.  See `:help b:match_ignorecase`.

These `b:match_*` variables should also be `:unlet` in the `b:undo_ftplugin` command.

2023-12-18 03:31 UTC, dkearns commented on runtime/ftplugin/erlang.vim
> +  let s:sw = &sw
This `s:sw` should be `:unlet` at some point, see `:help :unlet`.

> This is especially useful to clean up used global variables and script-local variables (these are not deleted when the script ends).

2023-12-19 19:16 UTC, hcs42 commented on runtime/ftplugin/erlang.vim
> +  let b:match_skip = 's:comment\|string\|erlangmodifier\|erlangquotedatom'
Thank you for your advice. I added `b:match_ignorecase` and updated `b:undo_ftplugin`.

2023-12-19 19:16 UTC, hcs42 commented on runtime/ftplugin/erlang.vim
> +  let s:sw = &sw
I added an `unlet` for `s:sw`.

2023-12-19 19:34 UTC, chrisbra commented
sorry, I did not notice earlier. Can you please make those two mentioned changes?

2023-12-19 20:58 UTC, hcs42 commented
@chrisbra: I made those changes, and pushed them to `hcs42:master` just 20 minutes before your comment. I didn't set the two review comments to "Resolved" because I thought that the reviewer might want to do that when they are satisfied with the changes.

2023-12-19 21:00 UTC, chrisbra commented
yeah no problem. Can you please make the following changes in addition?



- the shiftwidht() function is available since v7.3.694. I think by now we can assume it is always available :) So can you please remove the exists('*shiftwidth') ?

- Also, the exists("loaded_matchit") depends on the fact, that the matchit plugin wasn't loaded by the time the erlang filetype plugin has been loaded. I think we can just always define those b:match_.... (matchit specific buffer variables).
Then it should also work, when a user loads matchit later manually.

2023-12-20 12:16 UTC, hcs42 commented
I impemented @chrisbra 's suggestion. I saw @dkearns 's comment only afterwards. If you decide that it would be better to put back the `exists` guard in some form, just let me know.

2023-12-21 16:15 UTC, chrisbra commented
@dkearns thanks for letting me know. I'll await a new batch of updates then in the coming year :) 

In the meantime, I'll merge this now. Thanks everybody.

2023-12-21 16:16 UTC, merged