Odin lang filetype/syntax/indent plugin
vim/vim pull request #13867
Opened 2024-01-15 00:30 UTC by habamax

Vim has Odin filetype detection but misses actual Odin filetype, syntax and indent.

Repo: https://github.com/habamax/vim-odin

![image](https://github.com/vim/vim/assets/234774/18670dca-c732-4e9e-973f-5a93f29a7852)

![image](https://github.com/vim/vim/assets/234774/c7ed8f29-fece-45f9-a948-9d16fe4ad1e7)

2024-01-15 04:00 UTC, dkearns requested changes
Thanks, I was just watching an interview with the ginger one.

You're probably aware but Vim9-script runtime files won't be picked up by Neovim.  They're not rewriting them in legacy script.

2024-01-15 04:00 UTC, dkearns commented on runtime/ftplugin/odin.vim
> +# Language: odin
s/odin/Odin/

2024-01-15 04:00 UTC, dkearns commented on runtime/ftplugin/odin.vim
> +setlocal commentstring=//%s
Could we also set `comments` for formatting commands?

2024-01-15 04:00 UTC, dkearns commented on runtime/syntax/odin.vim
> +syntax region odinBlockComment start=/\v\/\*/ end=/\v\*\// contains=@Spell,odinTodo,odinBlockComment
The `\v` modifier isn't doing any work here.

2024-01-15 04:43 UTC, habamax commented
> Thanks, I was just watching an interview with the ginger one.

Indeed language looks promising.

> You're probably aware but Vim9-script runtime files won't be picked up by Neovim. They're not rewriting them in legacy script.

I think they can update it to legacy vimscript if needed? It shouldn't be too difficult, it is `GetOdinIndent()` function and a bit of script variable assignments here and there.

2024-01-15 06:15 UTC, habamax commented
found an issue with the last commit (wrt indentation), investigating.

2024-01-15 06:57 UTC, habamax commented
while cindent does almost what I think Odin needs, on edge cases it fails miserably. Let me convert this to draft for now, I will need to re-implement indentation algorithm from scratch.

2024-01-15 08:40 UTC, habamax commented
Indentation looks ok so far -- tested it on `demo.odin` bundled with the language.

2024-01-15 10:47 UTC, clason commented
> I think they can update it to legacy vimscript if needed? It shouldn't be too difficult, it is GetOdinIndent() function and a bit of script variable assignments here and there.

I won't, for the record; I'll just include the syntax file (and possibly the ftplugin; that indeed looks fairly trivial to translate back). Non-trivial vim9script files will be skipped until we get automated transpiling working (which is looking unlikely soon). If someone were to contribute a manual translation that is close enough to the original so changes can be backported (again, manually) easily, that could also be accepted. (Nobody has, so far, so there's no official policy around that yet.)

(Not complaining, to be clear; just wanted to let you know what is what from our side since you do take it into consideration -- which I appreciate. No hard feelings whatever you do!)

2024-01-16 16:33 UTC, chrisbra commented
Thanks!

2024-01-16 16:33 UTC, merged