runtime(vim): Distinguish Vim9 builtin object methods from namesake builtin functions
vim/vim pull request #14348
Opened 2024-03-30 20:41 UTC by zzzyxwvut

Currently, the overriding object method definitions are  
matched as `vimFunctionError` (`:help builtin-object-methods`,  
`v9.1.0148`).

For example:
```
vim9script

class Test
	def string(): string
		return "Test"
	enddef
endclass

echo string(Test.new()) == Test.new().string()
```

Instead, let's introduce a new syntax group `vimMethodName`  
and make these methods its members.  In order to emphasise  
the link between the overriding methods and the overridden  
functions for highlighting, `vimMethodName` is linked by  
default to `vimFuncName`.

2024-03-30 20:42 UTC, zzzyxwvut commented
@dkearns, @h-east, please review.

2024-03-31 08:57 UTC, dkearns requested changes
Thanks @zzzyxwvut this looks good to me.

I have a number of Vim9 fixes in the pipeline so it might be worth pinging me before working too hard on anything just to check it's not already incoming.  I'm just trying to save on duplicated work and am certainly not trying to discourage you.

2024-03-31 08:57 UTC, dkearns commented on runtime/syntax/generator/vim.vim.base
> +syn match	vimMethodName	contained	"\<\%(empty\|len\|string\)\>"
Is there a reason not to use syn-keyword rather than syn-match here?

2024-03-31 14:44 UTC, zzzyxwvut commented on runtime/syntax/generator/vim.vim.base
> +syn match	vimMethodName	contained	"\<\%(empty\|len\|string\)\>"
Ugh!  That is an overlooked vestige from another iteration:
`"\<def\s\+\zs\%(empty\|len\|string\)\>"` (before it was  
included into `vimUserFunc` as well).

2024-03-31 14:49 UTC, zzzyxwvut commented
Understood.  Next time around for the problem at hand, I'll  
look for the old issue to comment on, otherwise file a new  
one.  :)

I have applied the suggested changes and pushed them.

2024-03-31 16:24 UTC, chrisbra commented
thanks!

2024-03-31 16:26 UTC, merged