runtime(vim): add earthfile filetype
vim/vim pull request #14408
Opened 2024-04-04 05:18 UTC by glehmann

for https://earthly.dev/

2024-04-04 14:10 UTC, dkearns requested changes

2024-04-04 14:10 UTC, dkearns commented on runtime/filetype.vim
> +au BufNewFile,BufRead Earthfile setf earthfile
I'm sorry to do this to you but could you tab out the `setf` command to align with those above and below?

2024-04-04 20:11 UTC, glehmann commented on runtime/filetype.vim
> +au BufNewFile,BufRead Earthfile setf earthfile
I’d be pleased to do any required change, but I’m not sure to understand how to align `setf`: the command above and below are not at the same position, they are not preceded by the same number of space either. I fail to see the pattern to apply here :-/

2024-04-05 04:09 UTC, dkearns commented on runtime/filetype.vim
> +au BufNewFile,BufRead Earthfile setf earthfile
You probably have a different `tabstop` option value.  The file formatting assumes the default of 8.

There should be 3 tabs before `setf` in this case, rather than the single space, or you can apply the following patch.

Thanks.

```diff
diff --git a/runtime/filetype.vim b/runtime/filetype.vim
index 361e23ad5..40b17a0ef 100644
--- a/runtime/filetype.vim
+++ b/runtime/filetype.vim
@@ -666,7 +666,7 @@ au BufNewFile,BufRead *.dtd			setf dtd
 au BufNewFile,BufRead *.dts,*.dtsi,*.dtso,*.its	setf dts
 
 " Earthfile
-au BufNewFile,BufRead Earthfile setf earthfile
+au BufNewFile,BufRead Earthfile			setf earthfile
 
 " EDIF (*.edf,*.edif,*.edn,*.edo) or edn
 au BufNewFile,BufRead *.ed\(f\|if\|o\)		setf edif
```

2024-04-05 05:46 UTC, glehmann commented on runtime/filetype.vim
> +au BufNewFile,BufRead Earthfile setf earthfile
oh! Indeed my editor is configured with 4 spaces per tabs.

Sorry to have missed that both when editing the file and with you comment. It should be ok now :-)

2024-04-05 10:39 UTC, dkearns approved these changes
Thanks.

2024-04-05 17:54 UTC, closed without merging

2024-04-05 17:54 UTC, chrisbra commented
thanks!