ftplugin(gdb): add Matchit support
vim/vim pull request #14462
Opened 2024-04-09 13:19 UTC by Freed-Wu

2024-04-09 19:53 UTC, chrisbra commented
thanks. Can you please add a line like this one please: https://github.com/vim/vim/blob/9a91d2b72c20f213bbf77f27b7edd01e0e43d5e0/runtime/syntax/go.vim#L9

2024-04-10 04:42 UTC, Freed-Wu commented
Fixed.

2024-04-10 04:45 UTC, zeertzjq commented on runtime/ftplugin/gdb.vim
> +"               2024-03-17:          - add Matchit support (by Vim Project)
```suggestion
"               2024-04-10:          - add Matchit support (by Vim Project)
```

2024-04-10 04:51 UTC, Freed-Wu commented on runtime/ftplugin/gdb.vim
> +"               2024-03-17:          - add Matchit support (by Vim Project)
Fixed.

2024-04-10 12:13 UTC, dkearns requested changes

2024-04-10 12:13 UTC, dkearns commented on runtime/ftplugin/gdb.vim
> +setlocal include=^\s*source
```suggestion
setlocal include=^\\s*source
```

2024-04-10 12:13 UTC, dkearns commented on runtime/ftplugin/gdb.vim
> +  let b:match_words = '\<if\|while\|define\|document\>:\<else\>:\<end\>'
```suggestion
  let b:match_words = '\<\%(if\|while\|define\|document\)\>:\<else\>:\<end\>'
```

2024-04-10 20:44 UTC, closed without merging