ftplugin(asm): add Matchit support
vim/vim pull request #14461
Opened 2024-04-09 13:15 UTC by Freed-Wu

Refer https://github.com/vim/vim/blob/master/runtime/ftplugin/masm.vim#L18-L29

2024-04-09 19:54 UTC, chrisbra commented on runtime/ftplugin/asm.vim
> +" 		2024-04-09
by Vim Project (add matchit support)

2024-04-10 04:49 UTC, Freed-Wu commented on runtime/ftplugin/asm.vim
> +" 		2024-04-09
Fixed

2024-04-10 12:27 UTC, dkearns requested changes

2024-04-10 12:27 UTC, dkearns commented on runtime/ftplugin/asm.vim
> +" 		2024-04-09 by Vim Project (add Matchit support)
And then there were three date formats.

Can we please use YYYY Mon DD for the "Vim Project" lines?

2024-04-10 12:27 UTC, dkearns commented on runtime/ftplugin/asm.vim
> +setl include=^\s*%\s*include
```suggestion
setl include=^\\s*%\\s*include
```

2024-04-10 20:58 UTC, closed without merging