runtime: add PicoLisp filetype
vim/vim pull request #14476
Opened 2024-04-10 08:35 UTC by nat-418

This PR adds support for the [PicoLisp](https://picolisp.com/wiki/?home) programming language. PicoLisp exclusively uses the `*.l` filename extension, which is currently also used by Lex among several other extensions, so I have removed `*.l` from the Lex filename extensions and transferred it to PicoLisp.

2024-04-10 10:08 UTC, dkearns requested changes

2024-04-10 10:08 UTC, dkearns commented on runtime/filetype.vim
> +au BufNewFile,BufRead *.lex,*.lxx,*.l++		setf lex
You can't just steal the `*.l` extension for the new filetype, unless you're willing to fight off a horde of pitch-fork wielding Lex users.

You need to add a function to https://github.com/vim/vim/tree/master/runtime/autoload/dist/ft.vim that can determine the file type based on content heuristics and call that from the autocmd in filetype.vim.

2024-04-10 14:45 UTC, zeertzjq commented on runtime/autoload/dist/ft.vim
> +export def fttf()
This function name should not be changed
```suggestion
# Determine if a *.tf file is TF mud client or terraform
export def FTtf()
```

2024-04-10 14:47 UTC, nat-418 commented on runtime/filetype.vim
> +au BufNewFile,BufRead *.lex,*.lxx,*.l++		setf lex
I confess that I have never written vim9script before and I have forgotten what vimscript I once did know, so if the function I have added seems poor to you I apologize in advance. Essentially, I am trying to express the notion that, as a Lisp, a PicoLisp file should always begin with a leading `(` somewhere (excluding shebangs, etc.).

2024-04-10 14:48 UTC, zeertzjq commented on runtime/autoload/dist/ft.vim
> +    if firstcharacter !=? "("
```suggestion
    if firstcharacter ==? "("
```

2024-04-10 14:54 UTC, nat-418 commented on runtime/autoload/dist/ft.vim
> +export def fttf()
this was a mistake on my part, and I offer my apologies

2024-04-10 16:14 UTC, dkearns requested changes

2024-04-10 16:14 UTC, dkearns commented on runtime/autoload/dist/ft.vim
> +# Determne if a *.l file is Lex or PicoLisp
```suggestion
# Determine if a *.l file is Lex or PicoLisp
```

2024-04-10 16:14 UTC, dkearns commented on runtime/autoload/dist/ft.vim
> +  set ft=lex
```suggestion
  setf lex
```

All `set ft=` lines need to use `setf`.

2024-04-10 16:14 UTC, dkearns commented on runtime/autoload/dist/ft.vim
> +export def FTl()
There needs to be an option to override this behaviour with a global variable `g:filetype_l` like the `FTlsl` example.

This also needs to be documented at `:help filetype-overrule`.

2024-04-10 17:59 UTC, nat-418 commented
Thanks to @dkearns  and @zeertzjq for guiding me through this PR.

2024-04-10 20:21 UTC, chrisbra commented
thanks, but tests still seem to fail.

2024-04-11 19:28 UTC, chrisbra commented
test still fails :/

2024-04-13 23:16 UTC, zeertzjq commented on src/testdir/test_filetype.vim
> +    picolisp: ['file.l'],
```suggestion
```

2024-04-14 07:18 UTC, zeertzjq commented on runtime/autoload/dist/ft.vim
> +  for i in range(1, line("$"))
Many filetype detection functions have a limit to the number of lines to check, like using `range(1, min([line("$"), 100]))`

2026-06-13 20:15 UTC, chrisbra commented
this has stalled, so closing

2026-06-13 20:15 UTC, closed without merging