filetype: sometimes cabal config files are not recognized
vim/vim pull request #14498
Opened 2024-04-11 06:15 UTC by Freed-Wu

Problem: If users have a NFS mounted in /mnt, `/mnt/cabal/config` will not be recognized.
Solution: Improve the pattern for cabal config files.

2024-04-11 19:02 UTC, chrisbra requested changes

2024-04-11 19:02 UTC, chrisbra commented on runtime/filetype.vim
> -if exists('$XDG_CONFIG_HOME')
Don't remove this.

2024-04-12 04:27 UTC, Freed-Wu commented
> Don't remove this.

https://github.com/Freed-Wu/vim/blob/cabalconfig/runtime/filetype.vim#L957 will match them, too. IMO.

2024-04-12 18:28 UTC, Freed-Wu commented
Rebased.

2024-04-14 18:21 UTC, chrisbra commented
okay let me merge it

2024-04-14 18:23 UTC, closed without merging