finnish localisation
vim/vim pull request #14689
Opened 2024-05-01 09:28 UTC by ronin49

2024-05-01 09:36 UTC, chrisbra commented on runtime/lang/menu_fi_fi.latin1.vim
> +menutrans Toggle\ relati&ve\ Line\ Numbering<Tab>:set\ rnu!	Vaihda\ Suhteellinen\ rivinumerointi<Tab>:set\ nru!
please move above the `let &cpo` line

2024-05-01 16:13 UTC, chrisbra commented on runtime/lang/menu_fi_fi.latin1.vim
> +" Last Change:		1 May 2024
Please keep the existing style of the Last Change header, so change it to `2024 May 02`

2024-05-02 02:14 UTC, ronin49 commented
@chrisbra

2024-05-02 19:52 UTC, chrisbra commented
ping @flammie

2024-05-03 00:57 UTC, flammie requested changes

2024-05-03 00:57 UTC, flammie commented on runtime/lang/menu_fi_fi.latin1.vim
> -menutrans &Make<Tab>:make			&Make<Tab>:make
I think make here refers to kind of a make command of a build system and translating it would be just confusing.

2024-05-03 00:57 UTC, flammie commented on runtime/lang/menu_fi_fi.latin1.vim
> -menutrans Make					Make
same as above

2024-05-03 00:57 UTC, flammie commented on runtime/lang/menu_fi_fi.latin1.vim
> +menutrans &Show\ File\ Types\ in\ menu				N�yt�\ tiedostotyypit\ valikossa
Is this a machine translation? The word salad here makes no sense... 
Toggle Line Wrapping is "Vaihda rivitys"
Toggle Wrapping at word is "Vaihda rivittäminen sanojen kohdalta"
Toggle Tab Expanding is "Vaihda sarkainten laajennusta"

2024-05-03 05:36 UTC, chrisbra commented
closing for the reasons mentioned here https://github.com/vim/vim/pull/14703#issuecomment-2092337585

2024-05-03 05:36 UTC, closed without merging