feat(completion):  completeopt support fuzzy
vim/vim pull request #14878
Opened 2024-05-30 07:55 UTC by glepnir

draft .

2024-05-30 14:50 UTC, yegappan requested changes

2024-05-30 14:50 UTC, yegappan commented on src/insexpand.c
> +  return sa == sb ? 0 : sa < sb ? 1 : -1;
Is proper indentation (four spaces) used in this function?

2024-05-30 14:50 UTC, yegappan commented on src/insexpand.c
> +	{
The coding convention is to not use curly braces if there is a single statement in the body of a if statement.

2024-05-30 14:50 UTC, yegappan commented on src/insexpand.c
> +	if (compl_fuzzy_match == TRUE && compl_leader != NULL && lead_len > 0)
As "compl_fuzzy_match" is a boolean variable, there is no need to compare it against "TRUE".

2024-05-30 14:50 UTC, yegappan commented on src/insexpand.c
> +		    || (compl_fuzzy_match == TRUE && compl->cp_score > 0)))
No need to compare "compl_fuzzy_match" against TRUE.

2024-05-30 14:50 UTC, yegappan commented on src/insexpand.c
> +		    || (compl_fuzzy_match == TRUE && compl->cp_score > 0)))
Remove comparison to TRUE.

2024-05-30 14:50 UTC, yegappan commented on src/insexpand.c
> +	    if (!shown_match_ok && compl_fuzzy_match == FALSE)
Can you use "!compl_fuzzy_match" instead of comparing against FALSE?

2024-05-30 14:50 UTC, yegappan commented on src/insexpand.c
> +find_next_comp_when_fuzzy(void)
Can you add a test for this function?

2024-05-31 12:30 UTC, glepnir commented
I tried it briefly. but not sure yet because I don't fully understand some parts of the code ..

2024-06-01 13:06 UTC, glepnir commented
@chrisbra PTAL

2024-06-02 17:34 UTC, chrisbra commented on src/insexpand.c
> +static int pum_selected_item = -1;
shouldn't that be rather `compl_selected_item` to align with the other compl items? Also, please align with the other static ints above.

2024-06-02 17:34 UTC, chrisbra commented on src/testdir/test_ins_complete.vim
> +    let g:event = copy(v:event)
this seems unused?

2024-06-02 17:35 UTC, chrisbra commented
Thanks, I think it looks reasonable. Can you please also add some documentation at `:h 'completeopt'`?

2024-06-03 06:09 UTC, glepnir commented on src/insexpand.c
> +static int pum_selected_item = -1;
because this variable take from neovim  :)

2024-06-03 16:14 UTC, zeertzjq commented on src/testdir/test_ins_complete.vim
> +func Test_complete_fuzzy_match()
```suggestion
func Test_complete_fuzzy_match()
  new

```

2024-06-03 17:37 UTC, yegappan requested changes

2024-06-03 17:37 UTC, yegappan commented on src/insexpand.c
> +					    : compl_selected_item - 1;
Can you check the indentation for the lines in this function?  Vim source base uses four spaces for `shiftwidth`.

2024-06-03 17:37 UTC, yegappan commented on src/insexpand.c
> +    }
Can you remove the curly braces for this single statement if block?

2024-06-03 17:37 UTC, yegappan commented on src/insexpand.c
> +    static compl_T *
Can you add a comment above describing the functionality in this function?

2024-06-03 17:37 UTC, yegappan commented on src/insexpand.c
> +		if (compl->cp_score > max_fuzzy_score)
Can you add a comment here describing the functionality in this block?

2024-06-03 17:46 UTC, closed without merging

2024-06-03 17:47 UTC, chrisbra commented
Opps. sorry, I didn't see Yegappans comments here when I started mergin down this. @glepnir can you make the suggested changes in a follow-up patch please?

2024-06-03 17:48 UTC, chrisbra commented on src/testdir/test_ins_complete.vim
> +func Test_complete_fuzzy_match()
I fixed this locally when merging

2024-06-03 18:46 UTC, chrisbra commented on src/insexpand.c
> +    }
I'll fixed that already while mergin

2024-06-04 06:07 UTC, glepnir commented
will do