runtime: mediawiki
vim/vim pull request #15266
Opened 2024-07-15 00:28 UTC by avidseeker

Imported from: https://github.com/chikamichi/mediawiki.vim

See also: http://en.wikipedia.org/wiki/Wikipedia:Text_editor_support#Vim

2024-07-15 00:33 UTC, zeertzjq commented
There is a comment in filetype.vim:
```vim
" FlexWiki - disabled, because it has side effects when a .wiki file
" is not actually FlexWiki
"au BufNewFile,BufRead *.wiki			setf flexwiki
```

This apparently also applies to MediaWiki, so it seems that the filetype detection shouldn't be added.

2024-07-15 00:47 UTC, avidseeker commented
The plugin and the Wikipedia page suggests these file detection patterns:

```vim
if has("autocmd")
  au BufRead,BufNewFile *.mw             set filetype=mediawiki
  au BufRead,BufNewFile *.wiki           set filetype=mediawiki
  au BufRead,BufNewFile *.mediawiki      set filetype=mediawiki
  au BufRead,BufNewFile *.wikipedia.org* set filetype=mediawiki
  au BufRead,BufNewFile *.wikibooks.org* set filetype=mediawiki
  au BufRead,BufNewFile *.wikimedia.org* set filetype=mediawiki
endif
```
I'm not sure how common these are, but I think we can go with `*.mediawiki` and `*.mw`?

2024-07-15 00:52 UTC, avidseeker commented
I'd still argue for autodetecting `*.wiki` though. It's the most popular format and it is the format that proved itself. Flexwiki last update was [10 years ago](https://sourceforge.net/projects/flexwiki/).

> it has side effects when a .wiki file is not actually FlexWiki

There is no Wiki syntax than FlexWiki except for Mediawiki.

2024-07-15 01:03 UTC, zeertzjq commented
Oh, where seems to be a discussion about this in https://groups.google.com/g/vim_dev/c/jFJ_xRzY5aI/

2024-07-15 01:12 UTC, avidseeker commented
The discussion is from 2010, is it still relevant after 14 years? It seems to be a problem with the flexwiki ftplugin (setting bomb), not with having .wiki as mediawiki file format. In fact, it has a supporting sentiment to my suggestion: 

> Also, why is "flexwiki" the handler, when wikipedia is probably the most widely used wiki? 

I propose the same question.

> I think Flexwiki is dead or nearly so. It seems like mapping .wiki files to wikipedia (MediaWiki?)
> rather than Flexwiki is far more useful. Feel free to remove the flexwiki mapping from 
> ftplugin.vim.

If Flexwiki is dead or nearly so in 2010, then it's surely dead now.

> I can't find another file format that uses the .wiki extension.
> -- Bram 

> It's common to use the '.wiki' for any wiki text file; so making both it and '.mw' load MediaWiki syntax makes sense.

2024-07-15 11:17 UTC, jiangyinzuo requested changes

2024-07-15 11:17 UTC, jiangyinzuo commented on runtime/filetype.vim
> +au BufNewFile,BufRead *.mw		setf mediawiki
We can define the au command in just one line.
`au BufNewFile,BufRead *.mw,*.wiki setf mediawiki`

2024-07-15 11:17 UTC, jiangyinzuo commented on src/testdir/test_filetype.vim
> +    mediawiki: ['file.wiki'],
We should add both 'file.wiki' and 'file.mw' to the test

2024-07-15 18:40 UTC, chrisbra commented on runtime/ftplugin/mediawiki.vim
> +setlocal fileencoding=utf-8
I think fileencoding should not be set in a ftplugin.

2024-07-15 18:40 UTC, chrisbra commented on runtime/ftplugin/mediawiki.vim
> +setlocal formatoptions+=roq
formatoptions is already set a few lines above. Please move to that place

2024-07-15 18:40 UTC, chrisbra commented on runtime/ftplugin/mediawiki.vim
> +let b:undo_ftplugin += "setl commentstring< comments< formatoptions< foldexpr< fdm< fileencoding<"
b:undo_ftplugin is not initialized, I think this errors out with `E121: undefined variable`.

2024-07-15 18:40 UTC, chrisbra commented on runtime/ftplugin/mediawiki.vim
> +let b:undo_ftplugin += " matchpairs< formatoptions< linebreak< wrap< textwidth<"
'formatoptions is already reset i nthe line above

2024-07-15 18:40 UTC, chrisbra commented on runtime/ftplugin/mediawiki.vim
> +let b:undo_ftplugin += "setl commentstring< comments< formatoptions< foldexpr< fdm< fileencoding<"
also remove fileencoding here

2024-07-15 18:40 UTC, chrisbra commented on runtime/syntax/mediawiki.vim
> +if !exists("html_no_rendering")
this variable is not documented

2024-07-15 18:40 UTC, chrisbra commented on runtime/syntax/mediawiki.vim
> +  if !exists("html_my_rendering")
and so is this one

2024-07-16 11:19 UTC, chrisbra commented on runtime/ftplugin/mediawiki.vim
> +let b:undo_ftplugin = "setl commentstring< comments< formatoptions< foldexpr< fdm<"
Sorry I just noticed. We reset `'commentstring'` option, but never set it. I can remove this while merging, or do we want to explicitly also set the 'commentstring' option for mediawiki?

2024-07-16 11:28 UTC, avidseeker commented
According to https://mediawiki.org/wiki/Help:Formatting, mediawiki uses the same HTML commentstrings

<!-- This is a comment -->

On Tuesday, July 16th, 2024 at 06:19, Christian Brabandt ***@***.***> wrote:

> @chrisbra commented on this pull request.
> 
> In runtime/ftplugin/mediawiki.vim:
> 
> > @@ -41,5 +37,5 @@ endif
>  setlocal foldexpr=getline(v:lnum)=~'^\\(=\\+\\)[^=]\\+\\1\\(\\s*<!--.*-->\\)\\=\\s*$'?\">\".(len(matchstr(getline(v:lnum),'^=\\+'))-1):\"=\"
>  setlocal fdm=expr
> 
> -let b:undo_ftplugin += "setl commentstring< comments< formatoptions< foldexpr< fdm< fileencoding<"
> -let b:undo_ftplugin += " matchpairs< formatoptions< linebreak< wrap< textwidth<"
> +let b:undo_ftplugin = "setl commentstring< comments< formatoptions< foldexpr< fdm<"
> 
> Sorry I just noticed. We reset `'commentstring'` option, but never set it. I can remove this while merging, or do we want to explicitly also set the 'commentstring' option for mediawiki?
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.

2024-07-16 11:58 UTC, dkearns commented on runtime/ftplugin/mediawiki.vim
> +let b:undo_ftplugin = "setl commentstring< comments< formatoptions< foldexpr< fdm<"
```suggestion
let b:undo_ftplugin = "setl commentstring< comments< formatoptions< foldexpr< foldmethod<"
```

2024-07-16 19:03 UTC, chrisbra commented
thanks!

2024-07-16 19:12 UTC, closed without merging

2024-12-04 08:14 UTC, lilydjwg commented
For Chinese content, one needs to put `setl formatoptions< linebreak<` in `after/ftplugin/mediawiki.vim` to fix wrapping (assuming global `fo` is tuned for Chinese).