feat: add initial filetype plugin for autohotkey
vim/vim pull request #15345
Opened 2024-07-25 16:52 UTC by telemachus

2024-07-25 16:54 UTC, telemachus commented
This is a very minimal ftplugin, and I don't really want to be the maintainer (though I will if that's what it takes). But after looking at `runtime/ftplugin`, there seem to be many that are minimal. Also a search on GitHub turns up several examples of `autohotkey.vim` that include these comment settings.

2024-07-25 17:11 UTC, dkearns requested changes

2024-07-25 17:11 UTC, dkearns commented on runtime/ftplugin/autohotkey.vim
> +
```suggestion
```

The save/restore is only needed when using continuation lines which do not appear in this file.

2024-07-25 17:11 UTC, dkearns commented on runtime/ftplugin/autohotkey.vim
> +
```suggestion
```

2024-07-25 17:11 UTC, dkearns commented on runtime/ftplugin/autohotkey.vim
> +" Last Changed: 2024-07-25
```suggestion
" Last Change: 2024 Jul 25
```

2024-07-25 17:11 UTC, dkearns commented on runtime/ftplugin/autohotkey.vim
> +" Maintainer:   <Someone's name goes here>
The general rule has always been, I believe, that new runtime files need a maintainer.  Could you also add yourself to https://github.com/vim/vim/blob/master/.github/MAINTAINERS?  

Maybe the syntax file maintainer, @mmikeww, would be willing to take it on?

2024-07-25 17:11 UTC, dkearns commented on runtime/ftplugin/autohotkey.vim
> +" Language:     Autohotkey
```suggestion
" Language:     AutoHotkey
```

2024-07-25 17:22 UTC, telemachus commented on runtime/ftplugin/autohotkey.vim
> +
Cool. Thanks for saving me from cargo-culting my copy-pasta. :)

2024-07-25 17:24 UTC, telemachus commented on runtime/ftplugin/autohotkey.vim
> +" Maintainer:   <Someone's name goes here>
I'll take it for now then, and add my name to MAINTAINERS.

2024-07-25 17:28 UTC, telemachus commented
One last question for @dkearns: I was inclined to add `setlocal formatoptions+=croq`, but I could not decide if that was too opinionated. Let me know if you think I should add it (and the corresponding undo).

2024-07-25 18:14 UTC, mmikeww commented
i'm the current maintainer of the ahk syntax highlighting (https://github.com/mmikeww/autohotkey.vim), although all i've really done is just add new keywords onto the older maintainers work. and its mostly been just for ahk v1. i didnt even know that a filetype plugin was necessary

2024-07-25 19:22 UTC, telemachus commented
> i didnt even know that a filetype plugin was necessary

@mmikeww I could be wrong, but I believe you normally need (and have) both a `syntax/something.vim` and a `ftplugin/something.vim`. (And usually also `indent/something.vim` and others.) These files do different jobs.

> that syntax file should already be included with default vim, and commenting should work

The syntax file is there, and that handles detection of comments for highlighting. But more is required for commenting to work fully. A `ftplugin/something.vim` file normally sets both [`comments`](https://vimhelp.org/options.txt.html#%27comments%27) and [`commentstring`](https://vimhelp.org/options.txt.html#%27commentstring%27) (as this one does). Without those being set, vim falls back to defaults, and those defaults apply (I think) to C files. If those *are* set, then vim can do various things automatically (like correctly apply the comment marker to the next line) and plugins can interact with comments through scripting. At the moment, none of that applies to AutoHotkey files. (That's sort of how I ended up here: someone [filed a bug in neovim](https://github.com/neovim/neovim/issues/29853) because a built-in commenting plugin doesn't work with AutoHotkey files.

tl;dr the syntax file is only part of what AutoHotkey needs; this file will help add more capabilities for AutoHotkey files.

2024-07-26 04:34 UTC, mmikeww commented
thanks @telemachus 
if you want to submit the files to my repo, thats fine. or if you want to submit them here too. or if you want to take over maintainership of both this and also the syntax file, thats also fine by me. whatever you think is best, let me know

2024-07-26 10:20 UTC, telemachus commented
> i use the tcomment plugin with normal vim and i havent had a problem using gcc and the likes in order to comment ahk files

@mmikeww If I start vim without this added filetype plugin and run `:set commentstring?`, the result is `commentstring=/* %s */`. That's a default derived from C. So with tcomment installed, commenting will work in the sense that it gives me C-style comments. E.g., "This is a test" becomes "/* This is a test */". That (sort of? maybe?) works because AutoHotkey allows for multiline comments with `/*...*/` too. But (strictly speaking), AutoKey says that multiline comments "can be used to comment out an entire section, *but only if the symbols appear at the beginning of a line* (excluding whitespace)." With vim's defaults, that's not what you get as a result. Instead, you get a single-line comment with `/*` at the start and `*/` at the end. When you use tcomment, what kind of comments do you get? Also, I thought that the primary way to comment in AutoHotkey is single-line comments with `; `. That does not seem to be supported for me unless this filetype plugin is added. 

@dkearns I'm okay to maintain this for now. Let me know if you want me to make any other changes.

2024-07-26 13:54 UTC, dkearns approved these changes
> @dkearns I'm okay to maintain this for now. Let me know if you want me to make any other changes.

Thanks.  LGTM.

2024-07-26 14:21 UTC, telemachus commented
> Thanks.  LGTM.

Great. I will leave out the format options, so this is ready. Thanks again for review and guidance.

2024-07-26 14:41 UTC, mmikeww commented
@telemachus using `gcc` does use `;` for ahk comments for me, so maybe i've made other changes to my config somewhere to get that to happen, not sure

2024-07-26 17:24 UTC, chrisbra commented
thanks all!

2024-07-26 17:26 UTC, closed without merging