Set commentstring for nu filetype
vim/vim pull request #15601
Opened 2024-08-31 13:20 UTC by mrcjkb

2024-08-31 13:33 UTC, dkearns requested changes

2024-08-31 13:33 UTC, dkearns commented on runtime/ftplugin/nu.vim
> +" Language:	nu
```suggestion
" Language:	Nu
```

I do what I can...

2024-08-31 14:09 UTC, chrisbra commented
Thanks. Please also add yourself to the Maintainers file.

2024-08-31 17:47 UTC, chrisbra commented
I read https://programming-nu.github.io/syntax 
Is  `#` prefered as leading comment character (instead of using `;`)?

2024-08-31 17:51 UTC, mrcjkb commented
> I read https://programming-nu.github.io/syntax Is `#` prefered as leading comment character (instead of using `;`)?

I based this on [what they did in tree-sitter-nu](https://github.com/nushell/tree-sitter-nu/blob/0bb9a602d9bc94b66fab96ce51d46a5a227ab76c/plugin/init.lua#L5).

2024-09-01 07:19 UTC, chrisbra commented
alright thanks

2024-09-01 07:23 UTC, closed without merging