overhaul netrw's decompress
vim/vim pull request #16104
Opened 2024-11-22 06:56 UTC by Konfekt

addresses [0]

[0]: https://github.com/vim/vim/issues/16099

2024-11-22 17:14 UTC, saccarosium commented
`..` is the syntax for concatenating strings in vim9script with legacy vimscript it should be use `.` instead.

2024-11-22 17:18 UTC, saccarosium requested changes

2024-11-22 17:18 UTC, saccarosium commented on runtime/autoload/netrw.vim
> +            \ .."'.tar.lzma': '"..(has('unix')?"XZ_OPT=-T0":(has("win32") && &shell =~? '\vcmd(\.exe)?$' ?"setx XZ_OPT=-T0 &&":"")).." tar -xvf --lzma',"
Can you do the check for unix or windows once and than concatenate it? Also a bit of spacing in the concatenate would be nice... It is really hard to read.

2024-11-22 19:48 UTC, Konfekt commented
> .. is the syntax for concatenating strings in vim9script with legacy vimscript it should be use . instead.

I asked @chrisbra for it once, but it's been around for long enough

2024-11-23 03:59 UTC, 00-kat commented
The docs for `g:netrw_decompress` should probably be updated to show the new default too.

2024-11-23 12:20 UTC, chrisbra commented
thanks!

2024-11-23 12:28 UTC, closed without merging