Improve Chinese Simplified translation
vim/vim pull request #4407
Opened 2019-05-22 04:32 UTC by wbsdty331

Fix missing and improved some string.

2019-05-22 21:06 UTC, brammool commented
Can a native speaker please review and give comments?

2019-05-23 04:44 UTC, UncleBill commented on nsis/lang/simpchinese.nsi
> +    "添加右键菜单"
建议 “添加到快捷菜单”。

菜单并不一定只能通过右键弹出，有菜单键，另外可交互鼠标左右键

2019-05-23 04:44 UTC, UncleBill commented on nsis/lang/simpchinese.nsi
> +    "将“用 Vim 编辑”添加到系统右键菜单中。"
参考上条

2019-05-23 04:44 UTC, UncleBill commented on nsis/lang/simpchinese.nsi
> +    "正在反注册文件..."
建议 "正在移除注册文件..."

2019-05-23 04:47 UTC, UncleBill commented on nsis/lang/simpchinese.nsi
> +    "创建 Vim 的桌面快捷方式图标。"
如果 “创建 Vim 图标” 改为 “创建图标”，这里是否也可以把 “Vim” 去掉？或者两处都保留？

2019-05-23 04:51 UTC, wbsdty331 commented on nsis/lang/simpchinese.nsi
> +    "正在反注册文件..."
这个可行

2019-05-23 06:15 UTC, UncleBill commented on nsis/lang/simpchinese.nsi
> +    "显示 README 文件"
跟原意有些偏差，建议不修改

2019-05-23 06:15 UTC, UncleBill commented on nsis/lang/simpchinese.nsi
> +    "移除 Vim 的主目录，这将包含您的配置文件！"
“该目录包含...”

2019-05-23 06:15 UTC, UncleBill commented on nsis/lang/simpchinese.nsi
> +    "安装 Vim 图形界面及脚本。"
建议不去掉

2019-05-23 06:15 UTC, UncleBill commented on nsis/lang/simpchinese.nsi
> +    "安装 Vim 命令行程序 (vim.exe)。"
建议不去掉

2019-05-23 06:18 UTC, wbsdty331 commented on nsis/lang/simpchinese.nsi
> +    "显示 README 文件"
这个 `str_show_readme` 本来就是在安装最后的完成页面，我觉得这样应该也可以

2019-05-23 06:24 UTC, k-takata commented on nsis/lang/simpchinese.nsi
>      "&Compatibility and enhancements"
You may also want to translate this and rest of the messages.

2019-05-23 13:46 UTC, brammool commented
Obviously the remarks about the text need to be in Chinese, but can we have English remarks about whether it's ready to include or not?

2019-05-23 16:03 UTC, UncleBill commented on nsis/lang/simpchinese.nsi
> +    "显示 README 文件"
https://github.com/vim/vim/blob/44b210ccc3d6c5a890542f5f16cf807ddbe059f9/nsis/lang/english.nsi#L27

英文版也包含“安装完成后……”的意思，建议尊重原文。

>在安装最后的完成页面

包含了：在这个界面之后，安装程序可能还有别的操作。

希望再有人说下看法 @FelixZhang  @lilydjwg

2019-05-24 01:18 UTC, wbsdty331 commented on nsis/lang/simpchinese.nsi
>      "&Compatibility and enhancements"
This section I will get some help.

2019-05-24 01:20 UTC, wbsdty331 commented on nsis/lang/simpchinese.nsi
>      "&Compatibility and enhancements"
@UncleBill 这部分你可以翻译一下，这部分涉及到键盘映射和Vi/Vim行为

2019-05-24 05:21 UTC, lilydjwg requested changes

2019-05-24 05:21 UTC, lilydjwg commented on nsis/lang/simpchinese.nsi
> +    "显示 README 文件"
我支持旧翻译。「安装完成后显示自述文件」曾经是一个在 Windows 安装软件时很常见的选项。如果仅仅写「显示 README 文件」的话，我不太记得界面具体长什么样了，但对于不熟悉的人来说还是有些不明确。

2019-05-24 05:21 UTC, lilydjwg commented on nsis/lang/simpchinese.nsi
> +    "卸载旧版本的 Vim。"
不明确。「如果我没有安装旧版本的 Vim 怎么办？」建议「卸载系统上已存在的 Vim 版本」。上一个翻译同理。这里建议遵从原文，而且似乎也确实会卸载相同版本或者新版本的 Vim（我没有看到有版本检查）。

2019-05-24 05:21 UTC, lilydjwg commented on nsis/lang/simpchinese.nsi
> +    "安装 Vim 图形界面及脚本。"
建议「安装 Vim 图形界面及运行时文件。此项为必选。」

2019-05-24 05:21 UTC, lilydjwg commented on nsis/lang/simpchinese.nsi
> +    "安装 Vim 命令行程序 (vim.exe)。"
建议「Vim 控制台版本（vim.exe）。」严格地说，Vim 只有在 ex-mode 这种才是「命令行」程序。通常使用 Vim 的时候，既不是「命令」模式也不是面向「行」。

2019-05-24 05:21 UTC, lilydjwg commented on nsis/lang/simpchinese.nsi
> +    "正在移除注册文件..."
注册「文件」？建议遵从原文。

2019-05-24 17:58 UTC, wbsdty331 commented on nsis/lang/simpchinese.nsi
> -    "Unregistering..."
我想听一下你们对这里的`Register`和`Unregister`的看法

2019-05-25 04:54 UTC, lilydjwg commented on nsis/lang/simpchinese.nsi
> -    "Unregistering..."
正在注册/正在取消注册？
不过我没看到界面。

2019-05-26 10:03 UTC, wbsdty331 commented on nsis/lang/simpchinese.nsi
> -    "Unregistering..."
那我就先这么翻译了

2019-05-26 10:12 UTC, UncleBill commented on nsis/lang/simpchinese.nsi
>      "&Compatibility and enhancements"
不知道实际显示效果是什么样的？没有上下文，不好直接翻译

2019-05-26 10:15 UTC, wbsdty331 commented on nsis/lang/simpchinese.nsi
>      "&Compatibility and enhancements"
这个界面出现复制文件之前，设置好之后点next之后就直接开始复制文件了

2019-06-06 20:26 UTC, brammool commented
I have included the changes, thanks.  Will go out with the next runtime file update

2019-06-06 20:26 UTC, closed without merging