Fix indent for bzl files.
vim/vim pull request #8523
Opened 2021-07-07 19:55 UTC by chaoren

Fixes https://github.com/bazelbuild/vim-ft-bzl/issues/1.

Before this change:
```
cc_binary(
        name = "hello-world",
        srcs = ["hello-world.cc"],
        deps = [
                ":hello-time",
                "//lib:hello-greet",
                ],
        )
```
Indent is `shiftwidth() * 2` and the closing `)`/`]` don't match the
opening `(`/`[`.

After this change:
```
cc_binary(
    name = "hello-world",
    srcs = ["hello-world.cc"],
    deps = [
        ":hello-time",
        "//lib:hello-greet",
    ],
)
```

@dbarnett for maintainer approval.

2021-07-07 20:07 UTC, dbarnett requested changes
I think you should either change "maintainer" to not mention me and "https://github.com/google/vim-ft-bzl" OR make sure the same changes are submitted there, though. As-is this would leave us with your changes _here_ but not there and other changes _there_ but not here, while claiming that repo is related to maintainer on this file, which would be quite a mess for future contributors to try to make sense of.

2021-07-07 20:20 UTC, chaoren commented
Here's the same change for vim-ft-bzl: https://github.com/bazelbuild/vim-ft-bzl/pull/14

2021-07-07 20:21 UTC, chaoren commented
It probably doesn't make sense to replicate backwards compatibilty changes like `exists('*shiftwidth') ? 'shiftwidth()' : '&shiftwidth'` in vim-ft-bzl over here.

2021-07-07 22:36 UTC, dbarnett commented
> It probably doesn't make sense to replicate backwards compatibilty changes like `exists('*shiftwidth') ? 'shiftwidth()' : '&shiftwidth'` in vim-ft-bzl over here.

Oh okay, I noticed the differences and thought it was out of date / abandoned. Changes look reasonable to me.

2021-07-08 07:45 UTC, k-takata commented
Checking for `exists('*shiftwidth')` has been removed from all the Vim's runtime files a few years ago.

2021-07-08 09:32 UTC, brammool commented
I'll include it and update the date in the header.

2021-07-08 09:32 UTC, closed without merging